### ISSUE TITLE
Change .jscsrc rules for function declaration style

### ISSUE THREAD

**Issue by danasilver** [coursereviews/schedule#3]
Right now it requires:

``` js
function() {}
```

Should allow (maybe even require):

``` js
function () {}
```

http://javascript.crockford.com/code.html#function

`function` is a keyword and should be separated from the arguments list by spaces.

**Comment by danasilver** [comment]
@pbernasconi Thoughts?

**Comment by pbernasconi** [comment]
@danasilver I'm an advocate, and have always implemented it without a space `function() {}`. Maybe it's just out of habit, but all major front-end libraries follow this method to, eg: [React](https://github.com/facebook/react/blob/master/src/isomorphic/classic/class/ReactClass.js#L750), [Angular](https://github.com/angular/angular.js/blob/master/src/Angular.js#L145), [Backbone](https://github.com/jashkenas/backbone/blob/master/backbone.js#L78).

**Comment by danasilver** [comment]
:unamused: Eh. Okay. I'll get through it. Rather the code just be consistent.
